#!/bin/sh

set -eu

source_window=${1-}
target_window=${2-}

if [ -z "$source_window" ] || [ -z "$target_window" ]; then
    exit 0
fi

if [ "$source_window" = "$target_window" ]; then
    tmux set-option -qu -t "$target_window" @dragged_window
    exit 0
fi

source_index=$(tmux display-message -p -t "$source_window" '#{window_index}')
target_index=$(tmux display-message -p -t "$target_window" '#{window_index}')
session_id=$(tmux display-message -p -t "$target_window" '#{session_id}')

if [ "$source_index" -lt "$target_index" ]; then
    tmux move-window -a -s "$source_window" -t "$target_window"
else
    tmux move-window -b -s "$source_window" -t "$target_window"
fi

tmux move-window -r -t "$session_id:"
tmux select-window -t "$source_window"
tmux set-option -qu -t "$source_window" @dragged_window
