#! /bin/sh

# Setup monitors
# using xorg.conf.d now
#xrandr --output DisplayPort-0 --mode 1920x1080 --rate 144 --right-of HDMI-A-1

# If refreshing bspwm, remove all previous rules to prevent doubling up.
bspc rule -r "*"

# set root window cursor
xsetroot -cursor_name left_ptr

unfocused=#282c34
focused=#6eaafb

# bspwm config
bspc monitor DisplayPort-0 -d 1 2 3
bspc monitor HDMI-A-1 -d 4 5 6 

bspc config border_width         2
bspc config window_gap           8
bspc config normal_border_color	 $unfocused
bspc config active_border_color	 $unfocused
bspc config focused_border_color $focused

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc config focus_follows_pointer true
#bspc config pointer_follows_monitor true

# bspwm rules
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
bspc rule -a Pavucontrol state=floating
bspc rule -a Screenkey manage=off
# float bitwarden
bspc rule -a Chromium:crx_nngceckbapebfimnlniiiahkandclblb state=floating follow=on


### AUTOSTART ###

# Kill programs
killall -q picom
killall -q sxhkd
killall -q dunst
killall -q polkit-kde-authentication-agent-1
killall -q kdeconnect-indicator
killall -q pasystray
#killall -q polybar

# wait until the processes have been shut down (just in case)
while pgrep -u $UID -x picom >/dev/null; do sleep 1; done
while pgrep -u $UID -x sxhkd >/dev/null; do sleep 1; done
while pgrep -u $UID -x dunst >/dev/null; do sleep 1; done
while pgrep -u $UID -x pasystray >/dev/null; do sleep 1; done
while pgrep -u $UID -x polkit-kde-authentication-agent-1 >/dev/null; do sleep 1; done
#while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

# start sxhkd
sxhkd &

# set keymap
setxkbmap -layout 'de(qwerty)' &

# Wallpaper
nitrogen --restore &

# KDE Polkit and KWallet
/usr/lib/polkit-kde-authentication-agent-1 &
/usr/lib/pam_kwallet_init &

# Launch polybar on all monitors
polybar --reload bar1 &
polybar --reload bar2 &

# NetworkManager applet
nm-applet &

# Notifications
dunst &

# Compositor
picom &

# KDE Connect
kdeconnect-indicator &

# PulseAudio systray
pasystray &

# root window normal cursor
xsetroot -cursor-name left_ptr &
